name: Actualizar histórico diario

on:
  schedule:
    # todos los días a las 05:10 UTC (ajusta si quieres)
    - cron: "10 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Ejecutar actualizador
        run: |
          python update_historico.py

      - name: Commit & push si hay cambios
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: actualizar precio-aceite-historico.json [skip ci]"
            git push
          else
            echo "Sin cambios que commitear."
          fi
