name: Actualizar histórico

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"   # cada día 04:00 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependencias (si las hubiera)
        run: |
          python -m pip install --upgrade pip

      - name: Ejecutar actualizador
        run: |
          python convertir_historico.py
          echo "------ Listado de archivos en raíz tras convertir ------"
          ls -la
          echo "--------------------------------------------------------"
          test -f precio-aceite-historico.json && echo "OK: JSON generado"

      - name: Commit & push si cambió algo
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Actualizar JSON histórico (bot)"
            git push
          else
            echo "Sin cambios que commitear."
          fi
