name: Actualizar histórico a JSON

on:
  schedule:
    - cron: "5 6 * * *"     # cada día 06:05 UTC
  workflow_dispatch:        # ejecutable a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ejecutar conversión TXT -> JSON
        run: |
          python -V
          python update_historico.py

      - name: Commit & push si hay cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar JSON del histórico (auto)"
          file_pattern: "precio-aceite-historico.json"
